"""
PowerPoint and Word document builder.

Takes :class:`~claude_generator.PresentationContent` and populates:
- A PowerPoint template (.pptx) – one slide per generated slide
- A Word workbook template (.docx) – fills in the workbook intro and
  per-slide sections
"""

from __future__ import annotations

import logging
import os
from copy import deepcopy
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from claude_generator import PresentationContent

logger = logging.getLogger(__name__)

# MIME types used when uploading finished files to Google Drive
PPTX_MIME = (
    "application/vnd.openxmlformats-officedocument.presentationml.presentation"
)
DOCX_MIME = (
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
)


class PresentationBuilder:
    """
    Builds output files from a :class:`~claude_generator.PresentationContent`.

    Parameters
    ----------
    output_dir:
        Directory where generated files will be written.
    """

    def __init__(self, output_dir: str = "output") -> None:
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    # ------------------------------------------------------------------
    # PowerPoint
    # ------------------------------------------------------------------

    def build_presentation(
        self,
        content: "PresentationContent",
        template_path: str,
        output_filename: str | None = None,
    ) -> str:
        """
        Populate a .pptx template with *content*.

        The first slide in the template is used as the **title slide**
        (its title placeholder is replaced with the presentation title).
        The second slide (index 1) is used as a **content slide template**
        and is duplicated for each generated slide.  If the template only
        has one slide, every generated slide is created from scratch.

        Returns the path to the generated .pptx file.
        """
        try:
            from pptx import Presentation  # type: ignore[import]
            from pptx.util import Pt  # type: ignore[import]
        except ImportError as exc:
            raise ImportError(
                "python-pptx is required. Install it with: pip install python-pptx"
            ) from exc

        prs = Presentation(template_path)
        slide_layouts = prs.slide_layouts
        slides = prs.slides

        # ------ Title slide -------------------------------------------------
        title_slide = slides[0]
        _set_text_in_placeholder(title_slide, 0, content.title)
        # Attempt to clear/replace subtitle placeholder if present
        if len(title_slide.placeholders) > 1:
            _set_text_in_placeholder(
                title_slide,
                1,
                f"{len(content.slides)} slides  |  Generated by Claude",
            )

        # ------ Content slides ----------------------------------------------
        # Use slide layout index 1 (Title and Content) or the first layout
        # that has both a title and body placeholder.
        content_layout = _find_content_layout(slide_layouts)

        # Remove pre-existing content slides (indices >= 1) so we start clean
        # Note: python-pptx doesn't provide a remove method; we manipulate the
        # underlying XML directly.
        xml_slides = prs.slides._sldIdLst  # noqa: SLF001 (internal access needed)

        # Collect slide rIds to remove (all except the title slide)
        rids_to_remove = []
        for i, slide_elem in enumerate(list(xml_slides)):
            if i == 0:
                continue
            rids_to_remove.append(slide_elem.get("r:id"))

        for rid in rids_to_remove:
            # Remove the relationship entry
            rel = prs.slides.part.rels.get(rid)
            if rel:
                prs.slides.part.drop_rel(rid)
            # Remove the XML element
            for elem in list(xml_slides):
                if elem.get("r:id") == rid:
                    xml_slides.remove(elem)
                    break

        # Add a new slide for each generated slide
        for slide_content in content.slides:
            new_slide = prs.slides.add_slide(content_layout)
            _set_text_in_placeholder(new_slide, 0, slide_content.title)

            # Body placeholder (index 1)
            if len(new_slide.placeholders) > 1:
                body_ph = new_slide.placeholders[1]
                tf = body_ph.text_frame
                tf.clear()
                for i, bullet in enumerate(slide_content.bullets):
                    if i == 0:
                        tf.paragraphs[0].text = bullet
                    else:
                        para = tf.add_paragraph()
                        para.text = bullet
                    tf.paragraphs[i].level = 0

            # Speaker notes
            notes_slide = new_slide.notes_slide
            notes_tf = notes_slide.notes_text_frame
            notes_tf.text = slide_content.speaker_notes

        # ------ Save --------------------------------------------------------
        filename = output_filename or f"{_safe_filename(content.title)}.pptx"
        output_path = os.path.join(self.output_dir, filename)
        prs.save(output_path)
        logger.info("Presentation saved: %s", output_path)
        return output_path

    # ------------------------------------------------------------------
    # Word workbook
    # ------------------------------------------------------------------

    def build_workbook(
        self,
        content: "PresentationContent",
        template_path: str,
        output_filename: str | None = None,
    ) -> str:
        """
        Populate a .docx template with workbook content.

        The function looks for paragraph text that contains the placeholder
        tokens listed below and replaces them in-place.  If no placeholders
        are found the content is appended at the end of the document.

        Recognised placeholder tokens
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        ``{{PRESENTATION_TITLE}}``
            Replaced with the presentation title.
        ``{{WORKBOOK_INTRO}}``
            Replaced with the workbook introduction paragraph.
        ``{{SLIDES_CONTENT}}``
            Replaced with a section for each slide (title + bullets +
            speaker notes).

        Returns the path to the generated .docx file.
        """
        try:
            from docx import Document  # type: ignore[import]
            from docx.shared import Pt  # type: ignore[import]
        except ImportError as exc:
            raise ImportError(
                "python-docx is required. Install it with: pip install python-docx"
            ) from exc

        doc = Document(template_path)

        replaced: dict[str, bool] = {
            "{{PRESENTATION_TITLE}}": False,
            "{{WORKBOOK_INTRO}}": False,
            "{{SLIDES_CONTENT}}": False,
        }

        for para in doc.paragraphs:
            for token in list(replaced.keys()):
                if token in para.text:
                    if token == "{{PRESENTATION_TITLE}}":
                        _replace_paragraph_text(para, token, content.title)
                    elif token == "{{WORKBOOK_INTRO}}":
                        _replace_paragraph_text(para, token, content.workbook_intro)
                    elif token == "{{SLIDES_CONTENT}}":
                        _replace_paragraph_text(para, token, "")
                        _insert_slides_content_after(para, content, doc)
                    replaced[token] = True

        # If no placeholders found, append everything at the end
        if not any(replaced.values()):
            _append_full_workbook(doc, content)

        filename = output_filename or f"{_safe_filename(content.title)}_workbook.docx"
        output_path = os.path.join(self.output_dir, filename)
        doc.save(output_path)
        logger.info("Workbook saved: %s", output_path)
        return output_path


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _set_text_in_placeholder(slide: object, idx: int, text: str) -> None:
    """Set text on a slide placeholder identified by *idx*, ignoring errors."""
    try:
        ph = slide.placeholders[idx]  # type: ignore[index]
        ph.text = text
    except (IndexError, KeyError, AttributeError):
        pass


def _find_content_layout(layouts: object) -> object:
    """Return the first layout that has both title and body placeholders."""
    for layout in layouts:  # type: ignore[union-attr]
        ph_types = {ph.placeholder_format.idx for ph in layout.placeholders}
        if 0 in ph_types and 1 in ph_types:
            return layout
    return layouts[1] if len(layouts) > 1 else layouts[0]  # type: ignore[index]


def _safe_filename(title: str) -> str:
    """Convert a title string to a filesystem-safe filename stem."""
    safe = "".join(c if c.isalnum() or c in " -_" else "_" for c in title)
    return safe.strip().replace(" ", "_")[:80]


def _replace_paragraph_text(para: object, old: str, new: str) -> None:
    """Replace *old* with *new* inside a docx paragraph (preserves style)."""
    for run in para.runs:  # type: ignore[union-attr]
        if old in run.text:
            run.text = run.text.replace(old, new)


def _insert_slides_content_after(
    anchor_para: object, content: "PresentationContent", doc: object
) -> None:
    """Insert per-slide sections into *doc* directly after *anchor_para*."""
    try:
        from docx.oxml.ns import qn  # type: ignore[import]
        from lxml import etree  # type: ignore[import]
    except ImportError:
        return

    parent = anchor_para._element.getparent()  # type: ignore[union-attr]  # noqa: SLF001
    idx = list(parent).index(anchor_para._element)  # type: ignore[union-attr]  # noqa: SLF001

    insert_offset = 1
    for slide in content.slides:
        # Slide title paragraph
        heading_xml = (
            f'<w:p xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
            f'<w:pPr><w:pStyle w:val="Heading2"/></w:pPr>'
            f'<w:r><w:t>{slide.title}</w:t></w:r></w:p>'
        )
        heading_elem = etree.fromstring(heading_xml)
        parent.insert(idx + insert_offset, heading_elem)
        insert_offset += 1

        # Bullets
        for bullet in slide.bullets:
            bullet_xml = (
                f'<w:p xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
                f'<w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="1"/></w:numPr></w:pPr>'
                f'<w:r><w:t>{bullet}</w:t></w:r></w:p>'
            )
            bullet_elem = etree.fromstring(bullet_xml)
            parent.insert(idx + insert_offset, bullet_elem)
            insert_offset += 1

        # Speaker notes (italicised)
        notes_xml = (
            f'<w:p xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
            f'<w:r><w:rPr><w:i/></w:rPr><w:t>Speaker notes: {slide.speaker_notes}</w:t></w:r>'
            f'</w:p>'
        )
        notes_elem = etree.fromstring(notes_xml)
        parent.insert(idx + insert_offset, notes_elem)
        insert_offset += 1

        # Blank line between slides
        blank_xml = (
            '<w:p xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"/>'
        )
        blank_elem = etree.fromstring(blank_xml)
        parent.insert(idx + insert_offset, blank_elem)
        insert_offset += 1


def _append_full_workbook(doc: object, content: "PresentationContent") -> None:
    """Append all workbook content to *doc* when no placeholders are found."""
    doc.add_heading(content.title, level=1)  # type: ignore[union-attr]
    doc.add_paragraph(content.workbook_intro)  # type: ignore[union-attr]
    doc.add_paragraph("")  # type: ignore[union-attr]

    for slide in content.slides:
        doc.add_heading(slide.title, level=2)  # type: ignore[union-attr]
        for bullet in slide.bullets:
            doc.add_paragraph(bullet, style="List Bullet")  # type: ignore[union-attr]
        notes_para = doc.add_paragraph()  # type: ignore[union-attr]
        run = notes_para.add_run(f"Speaker notes: {slide.speaker_notes}")
        run.italic = True
        doc.add_paragraph("")  # type: ignore[union-attr]
